FROM ubuntu:20.04
LABEL mantainer="Vincenzo Palazzo vincenzopalazzodev@gmail.com"

ENV TZ=Europe/Minsk
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Ubuntu utils
RUN apt-get update && apt-get install -y \
    software-properties-common build-essential wget tar && \
    wget https://ziglang.org/builds/zig-linux-x86_64-0.10.0-dev.3315+1a16b7214.tar.xz && \
    tar -C /usr/local -xf zig-linux-x86_64-0.10.0-dev.3315+1a16b7214.tar.xz

# Install bitcoin core and lightningd (last version)
RUN add-apt-repository ppa:luke-jr/bitcoincore
RUN apt-get update  && apt-get install -y bitcoind libsodium-dev libpq-dev jq make

ENV CLIGHTNING_VERSION=0.11.2

RUN wget https://github.com/ElementsProject/lightning/releases/download/v$CLIGHTNING_VERSION/clightning-v$CLIGHTNING_VERSION-Ubuntu-20.04.tar.xz && \
    tar -xvf clightning-v$CLIGHTNING_VERSION-Ubuntu-20.04.tar.xz -C /opt && cd /opt && \
    mv usr clightning-v$CLIGHTNING_VERSION

RUN rm -r clightning-v$CLIGHTNING_VERSION-Ubuntu-20.04.tar.xz


ENV PATH $PATH:/usr/local/zig-linux-x86_64-0.10.0-dev.3315+1a16b7214/
ENV PATH=/opt/clightning-v$CLIGHTNING_VERSION/bin:$PATH

WORKDIR workdir

CMD ["./entrypoint.sh"]