name: Integration testing

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '30 1 1,15 * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Integration testing
        run: |
          cd docker
          docker-compose up --exit-code-from cln --quiet-pull
      - name: Upload lightning log
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          path: |
            docker/sandbox/node_one.log
            docker/sandbox/node_two.log
          name: ${{ github.run_number }}
